blockName = 'laser'
blockDef = {
	'mandatory'    :False,
	'allowMultiple':True,
	'parameters'   :[
		{ 'name'        :'boundary',
		  'dType'       :str,
		  'mandatory'   :True,
		  'allowedVals' :['x_min','x_max','y_min','y_max','z_min','z_max',
		                  'left','right','up','down','back','front'] },
		{ 'name'        :'amp',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','intensity'),('laser','intensity_w_cm2')],
		  'verification':lambda x: x> 0.0 },
		{ 'name'        :'intensity',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','amp'),('laser','intensity_w_cm2')],
		  'verification':lambda x: x> 0.0 },
		{ 'name'        :'intensity_w_cm2',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','amp'),('laser','intensity')],
		  'verification':lambda x: x> 0.0 },
		{ 'name'        :'id',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'omega',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','frequency'),('laser','lambda')],
		  'verification':lambda x: x>0.0 },
		{ 'name'        :'frequency',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','omega'),('laser','lambda')],
		  'verification':lambda x: x>0.0 },
		{ 'name'        :'lambda',
		  'dType'       :float,
		  'mandatory'   :True,
		  'alternatives':[('laser','omega'),('laser','frequency')],
		  'verification':lambda x: x>0.0 },
		{ 'name'        :'pol_angle',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'pol',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'phase',
		  'dType'       :(float,str),
		  'mandatory'   :False },
		{ 'name'        :'profile',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'t_profile',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'t_start',
		  'dType'       :(float,str),
		  'mandatory'   :False },
		{ 'name'        :'t_end',
		  'dType'       :(float,str),
		  'mandatory'   :False }
	]
}

