from . import shared

blockName = 'output'
blockDef = {
	'mandatory'    :False,
	'allowMultiple':True,
	'parameters'   :[
		{ 'name'        :'name',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'disabled',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dt_snapshot',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'nstep_snapshot',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'full_dump_every',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'restart_dump_every',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'force_first_to_be_restartable',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'force_last_to_be_restartable',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dump_first',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dump_last',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'time_start',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'time_stop',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'nstep_start',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'nstep_stop',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'dump_cycle',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dump_cycle_first_index',
		  'dType'       :int,
		  'mandatory'   :False },
		{ 'name'        :'dump_source_code',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dump_input_decks',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'dt_average',
		  'dType'       :float,
		  'mandatory'   :False,
		  'verification':lambda x: x>0.0 },
		{ 'name'        :'averaging_period',
		  'dType'       :float,
		  'mandatory'   :False,
		  'verification':lambda x: x>0.0 },
		{ 'name'        :'nstep_average',
		  'dType'       :int,
		  'mandatory'   :False,
		  'verification':lambda x: x>0 },
		{ 'name'        :'min_cycles_per_average',
		  'dType'       :int,
		  'mandatory'   :False,
		  'verification':lambda x: x>0 },
		{ 'name'        :'use_offset_grid',
		  'dType'       :bool,
		  'mandatory'   :False },
		{ 'name'        :'filesystem',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'file_prefix',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'particle_grid',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'px',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'py',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'pz',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'vx',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'vy',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'vz',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'charge',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'mass',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'particle_weight',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'ejected_particles',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'particle_energy',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'relativistic_mass',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'gamma',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'optical_depth',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'trident_optical_depth',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'qed_energy',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'id',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'grid',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'ex',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedvals' :shared.dumpmasks },
		{ 'name'        :'ey',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'ez',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'bx',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'by',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'bz',
		  'dType'       :str,
		  'mandatory'   :False},
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'jx',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'jy',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'jz',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'ekbar',
		  'dType'       :str,
		  'mandatory'   :False },
#		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'ekflux',
		  'dType'       :str,
		  'mandatory'   :False },
		 #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'mass_density',
		  'dType'       :str,
		  'mandatory'   :False },
	      #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'charge_density',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'number_density',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'temperature',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'poynt_flux',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'distribution_functions',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'particle_probes',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'absorbtion',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'total_energy_sum',
		  'dType'       :str,
		  'mandatory'   :False },
		  #'allowedVals' :shared.dumpMasks },
		{ 'name'        :'restartable',
		  'dType'       :bool,
		  'mandatory'   :False            },
		{ 'name'        :'rolling_restart',
		  'dType'       :bool,
		  'mandatory'   :False            },
		{ 'name'        :'nstep_accumulate',
		  'dType'       :int,
		  'mandatory'   :False            }
	]
}
