from . import shared

blockName = 'subset'
blockDef = {
	'mandatory'    :False,
	'allowMultiple':True,
	'parameters'   :[
		{ 'name'        :'name',
		  'dType'       :str,
		  'mandatory'   :True },
		{ 'name'        :'include_species',
		  'dType'       :str,
		  'mandatory'   :False },
		{ 'name'        :'dumpmask',
		  'dType'       :str,
		  'mandatory'   :False,
		  'allowedVals' :shared.dumpMasks },
		{ 'name'        :'random_fraction',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'x_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'x_max',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'y_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'y_max',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'z_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'z_max',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'px_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'px_max',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'py_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'py_max',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'pz_min',
		  'dType'       :float,
		  'mandatory'   :False },
		{ 'name'        :'pz_max',
		  'dType'       :float,
		  'mandatory'   :False },
	]
}
